### ISSUE TITLE
input file 

### ISSUE THREAD

**Issue by aguygarner** [stevemussmann/Comp-D#1]
Hi Steve, 
Should the input be a list of unlinked snps or all snps. It is unclear to me how linkage is considered from a phylip or str file and how bootstrapping would be considered from just a strict set of unlinked snps. What is being resampled and how, our heterozygous states?

**Comment by stevemussmann** [comment]
Hello,

My preference is to input unlinked SNPs as I feel it is more appropriate
(i.e., sampling of linked SNPs may introduce bias, especially if
disproportionately sampled from a particular region of the genome) but some
researchers will use all SNPs. I actually wrote the program originally
because pyRAD's implementation of D-statistic methods used all SNPs and I
was uncomfortable with doing that for my analyses.

As for bootstrapping, resampling occurs in the same way conducted in pyRAD,
which is similar to the implementation of bootstrapping in many
phylogenetic software packages. That is, columns of your SNP alignment are
resampled for the analysis.

I hope that helps,

-Steve
